# fly.toml app configuration file generated for website-for-my-wife on 2026-07-02T17:28:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'website-for-my-wife'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_PATH = '/data/app.db'
  PORT = '3000'
  TZ = 'Europe/Warsaw'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
