#!/bin/sh
# Nightly SQLite backup for personal-site.
#
# On the server this exact logic is generated by infra/cloud-init.yaml into
# /opt/personal/backup.sh and run by cron at 03:15 server time
# (/etc/cron.d/personal-backup). This repo copy is for reference / manual runs.
# Keeps the last 14 daily backups (deletes from the 15th oldest onward).
#
# ---------------------------------------------------------------------------
# ONE-TIME server secrets setup (run locally after `terraform apply`):
#
#   ssh root@$(terraform -chdir=infra output -raw server_ip) \
#     "cat > /opt/personal/.env" <<EOF
#   SESSION_SECRET=$(openssl rand -hex 32)
#   ADMIN_PASSWORD_HASH=$(node -e "console.log(require('bcryptjs').hashSync('REAL_PASSWORD_HERE', 12))")
#   EOF
#
# NOTE: the server .env holds the RAW bcrypt hash. docker-compose env_file does
# NOT perform $-expansion, so there is NO `\$` escaping here (unlike .env.local).
# ---------------------------------------------------------------------------

sqlite3 /opt/personal/data/app.db ".backup /opt/personal/backups/app-$(date +%F).db"
ls -t /opt/personal/backups/app-*.db | tail -n +15 | xargs -r rm
